/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package weatherapp;

import static org.junit.jupiter.api.Assertions.assertNotNull;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test void initializeGUI(){
        GUI gui = new GUI();
        assertNotNull(gui);
    }

    @Test void initializeAPICaller(){
        APICaller apiCaller = new APICaller();
        assertNotNull(apiCaller);
    }


}
